In [1]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
A.diagonal().sum()

15

In [3]:
B = np.matrix('[1,2,3;4,5,6;6,7,8]')
B

matrix([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])

In [4]:
B.diagonal()

matrix([[1, 5, 8]])

In [5]:
lst =B.tolist()
lst

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]

In [6]:
lst =A.tolist()
lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
lst=[1,2,3,4,5,6]

In [8]:
print(lst)

[1, 2, 3, 4, 5, 6]


In [9]:
A=np.array(lst)

In [10]:
A

array([1, 2, 3, 4, 5, 6])

In [11]:
type(A)

numpy.ndarray

In [12]:
lst=[[1,2,3],[4,5,6]]
lst

[[1, 2, 3], [4, 5, 6]]

In [13]:
B=np.matrix(lst)
B

matrix([[1, 2, 3],
        [4, 5, 6]])

## Lab 9
1. WAP to create a numpy array and find indices of non-zero elements
2. WAP to create a numpy to create a 3x3 identity matrix 
3. WAP to create a numpy to create a 3x3x3 array with random values
4. WAP to create a numpy to create a random vector of size 30 and find the mean value
5. WAP to create a numpy to multiply a 5x3 matrix by a 3x2 matrix 
6. WAP to create a numpy to input two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
7. WAP to print all the values of an array