In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
x = np.arange(1, 25).reshape(12, 2)
y = np.array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [3]:
y

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])

In [4]:
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [5]:
x_train

array([[ 1,  2],
       [13, 14],
       [17, 18],
       [ 3,  4],
       [19, 20],
       [23, 24],
       [21, 22],
       [ 7,  8],
       [11, 12]])

In [6]:
x_test

array([[ 5,  6],
       [ 9, 10],
       [15, 16]])

In [7]:
y_train

array([0, 0, 1, 1, 0, 0, 1, 0, 0])

In [8]:
y_test

array([1, 1, 1])

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=4, random_state=4)

In [16]:
x_train

array([[17, 18],
       [ 5,  6],
       [23, 24],
       [ 1,  2],
       [ 3,  4],
       [11, 12],
       [15, 16],
       [21, 22]])

In [17]:
x_test

array([[ 7,  8],
       [ 9, 10],
       [13, 14],
       [19, 20]])

In [21]:
y_train

array([1, 0, 1, 0, 1, 0, 0, 1])

In [22]:
y_test

array([0, 0, 1, 1])

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=4, random_state=4, stratify=y)

In [19]:
x_train

array([[21, 22],
       [ 1,  2],
       [15, 16],
       [13, 14],
       [17, 18],
       [19, 20],
       [23, 24],
       [ 3,  4]])

In [20]:
x_test

array([[11, 12],
       [ 7,  8],
       [ 5,  6],
       [ 9, 10]])

In [23]:
y_train

array([1, 0, 1, 0, 1, 0, 0, 1])

In [24]:
y_test

array([0, 0, 1, 1])

In [25]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, shuffle=False)

In [26]:
x_train

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [27]:
x_test

array([[17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [28]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [29]:
x = np.arange(20).reshape(-1, 1)
y = np.array([5, 12, 11, 19, 30, 29, 23, 40, 51, 54, 74, 62, 68, 73, 89, 84, 89, 101, 99, 106])
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [30]:
y

array([  5,  12,  11,  19,  30,  29,  23,  40,  51,  54,  74,  62,  68,
        73,  89,  84,  89, 101,  99, 106])

In [32]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=8, random_state=0)

In [34]:
model = LinearRegression().fit(x_train, y_train)
model.intercept_

3.1617195496417523

In [35]:
model.coef_

array([5.53121801])

In [36]:
model.score(x_train, y_train)

0.9868175024574795

In [37]:
model.score(x_test, y_test)

0.9465896927715023

In [38]:
y_pred=model.predict(x_test)

In [39]:
y_pred

array([102.72364381,   8.69293756, 108.25486182,  47.41146366,
        58.47389969,  97.19242579,  36.34902764,  75.06755374])

In [40]:
y_test

array([ 99,  12, 106,  51,  74, 101,  23,  73])

In [41]:
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
x, y = load_boston(return_X_y=True)

In [42]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=0)

In [43]:
from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(x_train, y_train)
model.score(x_train, y_train)

0.7668160223286261

In [44]:
model.score(x_test, y_test)

0.6882607142538012

In [45]:
y_pred = model.predict(x_test)

In [46]:
y_pred

array([24.58155243, 24.51629253, 29.71379915, 12.51132696, 21.34965428,
       19.05443022, 20.94614567, 20.95753329, 19.54644456, 20.53025981,
        6.96153725, 17.1707288 , 16.85608802,  5.74921859, 40.74378524,
       32.62964196, 22.88997064, 37.11387241, 30.94054261, 23.12796161,
       24.54411122, 25.50446659, 20.37697803, 30.82455449, 22.42949559,
       12.45993818, 17.10212725, 18.52819406, 34.91024736, 20.63587192,
       18.38567423, 17.65503994, 19.39633993, 23.8814007 , 29.06559846,
       19.49721361, 10.81151906, 25.66712254, 18.47597465, 15.40207099,
       26.55714333, 20.56301083, 21.8661955 , 16.10102382, 22.05244625,
       24.87100697, 19.97650209, 22.98518884,  9.46781454, 23.96350651,
       21.66355147, 16.95911711, 24.48952338, 28.692406  , 13.80788563,
       21.35149553, 20.72525415, 14.54282452, 16.61385208, 22.02338757,
       17.15670419, 21.27690041, 33.12409276, 31.40070549, 18.22591067,
       33.35335507, 18.26583607, 18.69440702, 19.46223051, 23.01

In [47]:
y_test

array([22.6, 50. , 23. ,  8.3, 21.2, 19.9, 20.6, 18.7, 16.1, 18.6,  8.8,
       17.2, 14.9, 10.5, 50. , 29. , 23. , 33.3, 29.4, 21. , 23.8, 19.1,
       20.4, 29.1, 19.3, 23.1, 19.6, 19.4, 38.7, 18.7, 14.6, 20. , 20.5,
       20.1, 23.6, 16.8,  5.6, 50. , 14.5, 13.3, 23.9, 20. , 19.8, 13.8,
       16.5, 21.6, 20.3, 17. , 11.8, 27.5, 15.6, 23.1, 24.3, 42.8, 15.6,
       21.7, 17.1, 17.2, 15. , 21.7, 18.6, 21. , 33.1, 31.5, 20.1, 29.8,
       15.2, 15. , 27.5, 22.6, 20. , 21.4, 23.5, 31.2, 23.7,  7.4, 48.3,
       24.4, 22.6, 18.3, 23.3, 17.1, 27.9, 44.8, 50. , 23. , 21.4, 10.2,
       23.3, 23.2, 18.9, 13.4, 21.9, 24.8, 11.9, 24.3, 13.8, 24.7, 14.1,
       18.7, 28.1, 19.8, 26.7, 21.7, 22. , 22.9, 10.4, 21.9, 20.6, 26.4,
       41.3, 17.2, 27.1, 20.4, 16.5, 24.4,  8.4, 23. ,  9.7, 50. , 30.5,
       12.3, 19.4, 21.2, 20.3, 18.8, 33.4, 18.5, 19.6, 33.2, 13.1,  7.5,
       13.6, 17.4,  8.4, 35.4, 24. , 13.4, 26.2,  7.2, 13.1, 24.5, 37.2,
       25. , 24.1, 16.6, 32.9, 36.2, 11. ,  7.2, 22

In [48]:
from sklearn.metrics import max_error
max_error(y_test,y_pred)

25.48370746890015

In [49]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.6882607142538012

In [51]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_pred)

3.6331273740246246

In [52]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_pred)

25.790362150702506

In [55]:
from math import sqrt
sqrt(mean_squared_error(y_test,y_pred))

5.0784212261984045

## Lab 17
1. WAP to perform Linear Regerssion on Diabetes Dataset and find the R sqaured score
2. WAP to perform Linear Regerssion on Diabetes Dataset and find the max error
3. WAP to perform Linear Regerssion on California Housing Dataset and find the RMSE, MAE and MSE