In [4]:
import numpy as np

In [5]:
A=np.array([1,4,6,7j])

In [6]:
print(A[2])

(6+0j)


In [7]:
print(A)

[1.+0.j 4.+0.j 6.+0.j 0.+7.j]


In [8]:
B=np.array([1,2,3,4.5,6.1])

In [9]:
B

array([1. , 2. , 3. , 4.5, 6.1])

In [10]:
A.shape

(4,)

In [11]:
B=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
B.shape

(3, 3)

In [14]:
C=np.array([[7,8,9],[4,5,6],[1,2,3]])

In [15]:
C.shape

(3, 3)

In [16]:
B+C

array([[ 8, 10, 12],
       [ 8, 10, 12],
       [ 8, 10, 12]])

In [17]:
B-C

array([[-6, -6, -6],
       [ 0,  0,  0],
       [ 6,  6,  6]])

In [18]:
B*C

array([[ 7, 16, 27],
       [16, 25, 36],
       [ 7, 16, 27]])

In [19]:
D=np.array([[1,2],[3,4],[4,5]])

In [20]:
C.shape

(3, 3)

In [21]:
D.shape

(3, 2)

In [22]:
C.dot(D)

array([[67, 91],
       [43, 58],
       [19, 25]])

In [23]:
A=np.array([1,2,3])
B=np.array([2,3,4])

In [24]:
np.add(A,B)

array([3, 5, 7])

In [25]:
np.subtract(A,B)

array([-1, -1, -1])

In [26]:
np.multiply(A,B)

array([ 2,  6, 12])

In [27]:
np.divide(A,B)

array([0.5       , 0.66666667, 0.75      ])

In [31]:
C=np.array([4,5,8])
np.mod(C,B)

array([0, 2, 0])

In [32]:
A=np.array([1,2,3,4j,6+3j])

In [33]:
A

array([1.+0.j, 2.+0.j, 3.+0.j, 0.+4.j, 6.+3.j])

In [35]:
np.real(A)

array([1., 2., 3., 0., 6.])

In [36]:
np.imag(A)

array([0., 0., 0., 4., 3.])

In [37]:
np.conj(A)

array([1.-0.j, 2.-0.j, 3.-0.j, 0.-4.j, 6.-3.j])

In [38]:
np.angle(A)

array([0.        , 0.        , 0.        , 1.57079633, 0.46364761])

In [40]:
np.power(B,2)

array([ 4,  9, 16])

In [49]:
np.random.random((2,3))

array([[0.23498425, 0.66567786, 0.75334562],
       [0.59623033, 0.53693389, 0.71844383]])

In [51]:
np.sum(B)

9

In [52]:
np.min(B)

2

In [53]:
np.max(B)

4

In [55]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [68]:
A=np.arange(9).reshape(3,3)

In [58]:
np.sqrt(B)

array([1.41421356, 1.73205081, 2.        ])

In [61]:
print(A)
print(A.T)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [70]:
print(A)
print(A.flat)
print(A.flat[5])
print(A.flatten())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
5
[0 1 2 3 4 5 6 7 8]


In [76]:
A.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [79]:
A=np.matrix('[1,2;3,4]')
print(A)

[[1 2]
 [3 4]]


In [80]:
B=np.matrix('[1,2,3;5,6,7]')
print(B)

[[1 2 3]
 [5 6 7]]


In [82]:
A*B

matrix([[11, 14, 17],
        [23, 30, 37]])

In [83]:
A.T

matrix([[1, 3],
        [2, 4]])

In [84]:
A.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [87]:
A + A.T

matrix([[2, 5],
        [5, 8]])

## Lab 8
1. WAP using numpy input two arrays as A=(1,0) and B=(0,1) and calcuate two new arrays as
    C = 1/sqrt(2)(A+B)
    D = 1/sqrt(2)(A+B)
2. WAP using numpy to create a matrix A of 2x2 then find the size of A and print element (1,1) of A
3. WAP using numpy to find an element in an array
4. WAP using numpy to sort an array
5. WAP using numpy to sort a 2D array
6. WAP using numpy to add elements of diagnols
7. WAP using numpy to add elements of diagnols and find which one is greater