In [3]:
import numpy as np
#from math import sqrt

In [4]:
A=np.array([1,0])
A

array([1, 0])

In [5]:
B=np.array([0,1])
B

array([0, 1])

In [6]:
C=np.sqrt(2)*(A+B)
C=1/C
C

array([0.70710678, 0.70710678])

In [8]:
D=np.sqrt(2)*(A-B)
D=1/D
D

array([ 0.70710678, -0.70710678])