In [1]:
import numpy as np

In [8]:
A=np.array([1,6,3,1,7,4,9,4,6,2,1])
B=np.matrix('[1,2,3;1,2,3]')
print(A)
print(B)

[1 6 3 1 7 4 9 4 6 2 1]
[[1 2 3]
 [1 2 3]]


In [16]:
res1 = np.where(A == 1)
print('Tuple of arrays returned : ', res1)
print("Value 1 exists at following indices", res1[0], sep='\n')

res2 = np.where(B == 1)
print('\nTuple of arrays returned : ', res2)
print("Value 1 exists at following indices", res2[0], sep='\n')

Tuple of arrays returned :  (array([ 0,  3, 10], dtype=int64),)
Value 1 exists at following indices
[ 0  3 10]

Tuple of arrays returned :  (array([0, 1], dtype=int64), array([0, 0], dtype=int64))
Value 1 exists at following indices
[0 1]
