In [2]:
import numpy as np 
  
arr = np.array([[55, 25, 15], 
                [30, 44, 2], 
                [11, 45, 77]]) 
  
print("Matrix is:") 
print(arr) 
  
# Finding the diagonal elements of a matrix 
diag = np.diagonal(arr)  

#If a is 2-D and not a matrix,  a 1-D array of the same type as a containing the diagonal is returned. 
#If a is a matrix, a 1-D array containing the diagonal is returned in order to maintain backward compatibility.
#If the dimension of a is greater than two, then an array of diagonals is returned, packed from
  
print("\nDiagonal elements are:") 
print(diag) 
  
print("\nSum of Diagonal elements is:") 
print(sum(diag)) 

Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Diagonal elements are:
[55 44 77]

Sum of Diagonal elements is:
176


In [3]:
a = np.array([[55, 25, 15], 
              [30, 44, 2], 
              [11, 45, 77]]) 
  
print("Numpy Matrix is:") 
print(a) 
  
trace = np.trace(a) #trace of an n by n square matrix A is defined to be 
                    #the sum of the elements on the main diagonal 
  
print("\nTrace of given 3X3 matrix:") 
print(trace) 

Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Trace of given 3X3 matrix:
176


diag
MATLAB work-a-like for 1-D and 2-D arrays.

diagflat
Create diagonal arrays.

trace
Sum along diagonals.