In [3]:
import numpy as np 
  
arr = np.array([[55, 25, 15], 
                [30, 44, 2], 
                [11, 45, 77]]) 
  
print("Matrix is:") 
print(arr) 
  
# Finding the diagonal elements of a matrix 
diag = np.diagonal(arr) 
  
print("\nDiagonal elements are:") 
print(diag) 
  
print("\nSum of Diagonal elements is:") 
print(sum(diag)) 

Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Diagonal elements are:
[55 44 77]

Sum of Diagonal elements is:
176
