In [3]:
import numpy as np
from numpy.linalg import inv
a = np.array([[5., 3., 1.], [3., 9., 4.], [1., 3., 5.]])
print(a, '\n')
 
ainv = inv(a)
ainv = ainv.round(3)
 
print(ainv)

[[5. 3. 1.]
 [3. 9. 4.]
 [1. 3. 5.]] 

[[ 0.25  -0.091  0.023]
 [-0.083  0.182 -0.129]
 [ 0.    -0.091  0.273]]
