In [4]:
import numpy as np
arr = np.array([[0, 8, 0],
                [7, 0, 0], 
                [-5, 0, 1]]) 
  
print ("Array : \n", arr) 
    
res = np.nonzero(arr)
print ("Result : ", res)  
print ("Rows of non zero elements : ", res[0])  
print ("Columns of non zero elements : ", res[0])  

Array : 
 [[ 0  8  0]
 [ 7  0  0]
 [-5  0  1]]
Result :  (array([0, 1, 2, 2], dtype=int64), array([1, 0, 0, 2], dtype=int64))
Rows of non zero elements :  [0 1 2 2]
Columns of non zero elements :  [0 1 2 2]
