numpy.identity(n, dtype = None) : Return a identity matrix i.e. a square matrix with ones on the main diagonal

Parameters : 
n     : [int] Dimension n x n of output array  
dtype : [optional, float(by Default)] Data type of returned array

Returns : 
identity array of dimension n x n,  with its main diagonal set to one, and all other elements 0


In [6]:
import numpy as np
 
mat = np.identity(3, dtype = float)
print("Matrix : \n", mat)

Matrix : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
