In [2]:
import numpy as np
arr = np.random.random((3,3,3))
print(arr)

[[[0.96381315 0.64986708 0.92304064]
  [0.25996577 0.51639614 0.90199598]
  [0.42483881 0.41548154 0.84742033]]

 [[0.60475743 0.14742504 0.63930891]
  [0.07347486 0.91123198 0.95165935]
  [0.12694956 0.51647101 0.51600337]]

 [[0.21896916 0.65308311 0.45079443]
  [0.53726997 0.73056902 0.75187488]
  [0.75901839 0.52670147 0.17142746]]]
