In [8]:
import numpy as np

A=np.arange(15).reshape(5,3)
print(A)

B=np.arange(6).reshape(3,2)
print(B)

res = np.dot(A,B) 
print(res)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]
