In [1]:
import numpy as np

X = np.array([1,2,3,4]) 
Y = np.array([5,6,7])

X = X.reshape((-1,1))
print("\n", X)

diff_matrix = X-Y
print("\n", diff_matrix)

cauchym = 1.0/diff_matrix
print("\n", cauchym)



 [[1]
 [2]
 [3]
 [4]]

 [[-4 -5 -6]
 [-3 -4 -5]
 [-2 -3 -4]
 [-1 -2 -3]]

 [[-0.25       -0.2        -0.16666667]
 [-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]
